### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by fsantanna** [rasantana/EDL#1]
Por favor formatar o texto dos dois trabalhos com Markdown:
http://daringfireball.net/projects/markdown/

**Comment by fsantanna** [comment]
O arquivo tem que ter a extensão `.md` para ser interpretado corretamente.
(você não está verificando o resultado??)

**Comment by rasantana** [comment]
Tinha excluído e feito de novo pro artigo, acabei esquecendo de por o .md

Ambos estão com a formatação agora.
